name: GitHub Actions Demo
on: 
  push:
    branches:  [ main ]
    paths-ignore: [ .github/** ]  
  pull_request:
    branches: [ 'main' ]
  schedule:
    - cron: '15 6 * * 0'
    
  workflow_dispatch:
    inputs:
      env: 
        description: Environment to deploy to
        type: string
        required: true
    
jobs:
  Build:
    runs-on: 'ubuntu-latest'
    steps:
      - run: | 
          echo "Job triggered by: ${{ github.event_name }}"
          echo "Current branch is ${{ github.ref }} on repo ." 
        
      - uses: actions/checkout@v3.3.0
      
      - name: List files in repo
        run: |
          echo "The repo  ${{ github.repository }} has the folllowing files:"
          tree

  Test: 
      runs-on: ubuntu-latest
      if: ${{ github.event_name == "workflow_dispatch" }}
      needs: Build
      environment: Test
      steps:
        - run: echo "Testing..."

  Load-Test: 
      runs-on: ubuntu-latest
      if: ${{ github.event_name == "workflow_dispatch" }}
      needs: Build
      environment: Load-Test
      steps:
        - run: |
            echo "Testing..."
            sleep 15

  Production: 
      runs-on: ubuntu-latest
      if: ${{ github.event.inputs.env == "Production" }}
      needs: [ Test, Load-Test ]
      environment: 
        name: Production
        url: https://writeabout.net
      strategy:
        matrix:
          i: [1, 2, 3, 4, 5]

      steps:
        - run: |
            echo "Step ${{ matrix.i }} deploying..."
            sleep 10


      
