name: GitHub Actions Demo
on: 
  push:
    branches:  [ main ]
    paths-ignore: [ .github/** ]  
  pull_request:
    branches: [ 'main' ]
  schedule:
    - cron: '15 6 * * 0'
    
  workflow_dispatch:
    
jobs:
  Build:
    runs-on: 'ubuntu-latest'
    steps:
      - run: | 
          echo "Job triggered by: ${{ github.event_name }}"
          echo "Current branch is ${{ github.ref }} on repo ." 
        
      - uses: actions/checkout@v3.3.0
      
      - name: List files in repo
        run: |
          echo "The repo  ${{ github.repository }} has the folllowing files:"
          tree
      
